In [580]:
from IntegralQuery import SearchQuery, IntegralQuery, Filter, Range #################################################
import numpy as np
from dataclasses import dataclass
import astropy.units as u
from astropy.coordinates import SkyCoord
from datetime import datetime
from numba import njit, vectorize



@njit
def calculate_distance_matrix(quick_list, angle_weight, time_weight, max_distance):
    l = len(quick_list)
    distances = np.full((l,l), 2*max_distance)
    
    partitions = [0]
    for i in range(1,l):
        if quick_list[i,2]-quick_list[i-1,2] > max_distance/time_weight:
            partitions.append(i)
    partitions.append(l)
    
    for i in range(len(partitions)-1):
        for j in range(partitions[i], partitions[i+1]):

            for k in range(j+1, partitions[i+1]):
                distances[j,k] = distances[k,j] = calculate_distance(quick_list[j],quick_list[k],
                                                                     angle_weight,time_weight)
                
    np.fill_diagonal(distances,0.)
            
    return np.array(partitions), distances

@njit
def calculate_distance(point1, point2, angle_weight, time_weight):
    ang_dis = np.arccos( np.sin(point1[1])*np.sin(point2[1]) # Large Error for very small angles
                        + np.cos(point1[1])*np.cos(point2[1]) * np.cos(point1[0] - point2[0]) )
    time_dis = abs(point1[2] - point2[2])
    return ( (angle_weight*ang_dis)**2 + (time_weight*time_dis)**2 )**0.5

@njit
def find_regions(distances, max_distance, partitions):
    regions = []
    for i,partition in enumerate(partitions[:-1]):
        unconnected = [j for j in range(partition, partitions[i+1])]
        while not len(unconnected)==0:
            temp_region = [unconnected.pop(0)]
            search_index = 0
            while search_index < len(temp_region):
                l = len(unconnected)
                for j in range(l-1,-1,-1):
                    if distances[ temp_region[search_index], unconnected[j] ] < max_distance:
                        temp_region.append(unconnected.pop(j))
                search_index += 1
            regions.append(sorted(temp_region))
    return regions

@njit
def choose_random_weighted_interval(weights):
    r = np.random.random(1)[0] * np.sum(weights)
    s = 0.
    for i, w in enumerate(weights):
        s += w
        if r < s:
            return i
        
@njit
def calc_pair_combinations(number):
    return (number)*(number-1)/2
    
    

class Cluster:
    def __init__(self,
                 pointing,
                 region):
        self.indices = [pointing.index]
        self.avg_distance = 0.
        self.num_pointings = 1
        self.pointings = [pointing]
        self.region = region
        
    def add_pointing(self, pointing):
        self.avg_distance = self.calc_new_avg_dist(pointing)
        self.indices.append(pointing.index)
        self.pointings.append(pointing)
        self.num_pointings += 1
        
    def should_add_pointing(self, pointing):
        if self.num_pointings < self.region.query._cluster_size_range[1]:
            if self.find_new_max_dist(pointing) < self.region.query._max_distance:
                if self.num_pointings >= self.region.query._cluster_size_range[0]:
                    if (self.calc_new_avg_dist(pointing)/self.avg_distance 
                        < self.region.query._cluster_size_preference_threshold[self.num_pointings 
                                                                                - self.region.query._cluster_size_range[0]]):
                        return True
                else:
                    return True
        return False
    
        
    def dissolve_cluster(self):
        for p in self.pointings:
            p.cluster = None
            
        
        
    def calc_new_avg_dist(self, pointing):
        return ((self.avg_distance * calc_pair_combinations(self.num_pointings)
                 + np.sum(self.region.query._distances[pointing.index,self.indices]))
                 / calc_pair_combinations(self.num_pointings+1) )
        
    def find_new_max_dist(self, pointing):
        temp_indices = self.indices.copy()
        temp_indices.append(pointing.index)
        return np.amax(self.region.query._distances[temp_indices,:][:,temp_indices])

    def find_closest_pointings(self, cluster2):
        d = self.region.query._distances[self.indices,:][:,cluster2.indices]
        print(d)
        c = np.unravel_index(d.argmin(), d.shape)
        print(c)
        return self.pointings[c[0]], cluster2.pointings[c[1]]
    
        

@dataclass
class Pointing:
    '''
    Dataclass that represents a single Pointing
    '''
    scw_id: str
    sky_coords: SkyCoord
    start_time: datetime
    index: int
    cluster: Cluster = None
    cluster2: Cluster = None ############ Reset this, delete unnecessary clusters and regions ##############################################
    
    def distance_calculator(self, pointing2, angle_weight: float, time_weight: float): #####################################################
        return ( (angle_weight * self.sky_coords.separation(pointing2.sky_coords).deg)**2
                + (time_weight * abs( (self.start_time - pointing2.start_time).total_seconds()/86400 ) )**2 )**0.5
        
    def angle_between_three_pointings(self, pointing2, pointing3):
        pass #####################






class ClusteredQuery:
    def __init__(self,
                 scw_ids, # Has to be sorted by START_DATE
                 angle_weight,
                 time_weight,
                 max_distance,
                 cluster_size_range = (3,5),
                 cluster_size_preference_threshold = (3,3),
                 failed_improvements_max = 4,
                 suboptimal_cluster_size_range = (1,2), #has to start at 1
                 close_suboptimal_cluster_size_range = (1,3) # above has to be subset
                 ):
        """
        Init the Clustered Query object. Used to cluster pointings
        
        """
        self._max_distance = float(max_distance)
        self._cluster_size_range = cluster_size_range
        self._cluster_size_preference_threshold = cluster_size_preference_threshold
        self._failed_improvements_max = failed_improvements_max
        self._suboptimal_cluster_size_range = suboptimal_cluster_size_range
        self._close_suboptimal_cluster_size_range = close_suboptimal_cluster_size_range
        
        self._num_pointings = len(scw_ids)
        
        self.quick_list = np.zeros((self._num_pointings, 3))
        self.quick_list[:,0:2] = scw_ids[:,1:3]
        for i in range(self._num_pointings):
            self.quick_list[i,2] = (scw_ids[i,3] - datetime(2000,1,1,0,0,0)).total_seconds()/86400
            
        partitions, self._distances = calculate_distance_matrix(self.quick_list, angle_weight, time_weight, self._max_distance)
        
        self._sortable_distances = np.concatenate((self.distances,np.array([np.arange(self._num_pointings)]).T),axis=1) ################# point?
        
        self._region_indices = find_regions(self._distances, self._max_distance, partitions)
        
        
        self._pointings = np.array([Pointing(pointing[0],
                                            SkyCoord(pointing[1],pointing[2],frame="icrs",unit="deg"),
                                            pointing[3], index)
                                    for index, pointing in enumerate(scw_ids)])
                
        self._regions = []
        
        for i in self._region_indices:
            self._regions.append(Region(i, self))
            
    
    
    @property
    def pointings(self):
        """
        :returns: Base List of Pointings
        """
        return self._pointings
    
    @property
    def distances(self):
        """
        :returns: Base Distance Matrix of Pointings
        """
        return self._distances
    

    
    
class Region:
    def __init__(self,
                 region_indices,
                 query
                 ):
        self.indices = region_indices
        
        self.query = query
        
        self.distances = query._distances[self.indices,:][:,self.indices] ############ point?
        self.sortable_distances = np.concatenate((self.distances,np.array([self.indices]).T),axis=1) # Adds indices as right column, sort using a[a[:,x].argsort()]
        
        self.clusters = {}
        self.potential_clusters1 = {}
        self.potential_clusters2 = {}
        for i in range(query._cluster_size_range[1]):
            self.clusters[i+1]=[]
            self.potential_clusters1[i+1]=[]
            self.potential_clusters2[i+1]=[]
            

        
        self.initial_clustering()
        
        for key, value in self.clusters.items():
            for c in value:
                print(f"{c.indices}, {c.avg_distance}")
        print(self.has_suboptimal_clusters())
        
        self.attempt_improvement()
        
        # failed_improvements = 0
        # while failed_improvements < self.query._failed_improvements_max and self.has_suboptimal_clusters():
        #     if not self.attempt_improvement():
        #         failed_improvements += 1
        #     else:
        #         failed_improvements = 0
        
    
    def initial_clustering(self):
        cluster = Cluster(self.query._pointings[self.indices[0]], self)
        for index in self.indices[1:]:
            if cluster.should_add_pointing(self.query._pointings[index]):
                cluster.add_pointing(self.query._pointings[index])
            else:
                self.clusters[cluster.num_pointings].append(cluster)
                cluster = Cluster(self.query._pointings[index], self)
        self.clusters[cluster.num_pointings].append(cluster)
        
    def attempt_improvement(self):
        c1 = self.find_suboptimal_cluster()
        c2 = self.find_close_suboptimal_cluster(c1)
        if not self.find_cluster_path(c1,c2):
            return False
        
    
    def find_suboptimal_cluster(self):
        size_weights = np.array([len(self.clusters[i]) / i**2
                                 for i in range(self.query._suboptimal_cluster_size_range[0],
                                                self.query._suboptimal_cluster_size_range[1] + 1)])
        size = choose_random_weighted_interval(size_weights) + 1
        index = np.random.randint(len(self.clusters[size]))
        cluster = self.clusters[size].pop(index)
        self.potential_clusters1[size].append(cluster)
        return cluster
    
    def find_close_suboptimal_cluster(self, cluster):
        clusters = []
        cluster_size_indices = [0]
        for i in range(self.query._close_suboptimal_cluster_size_range[0], 
                       self.query._close_suboptimal_cluster_size_range[1] + 1):
            clusters.extend(self.clusters[i])
            cluster_size_indices.append( len(self.clusters[i]) + cluster_size_indices[i-1] )
        cluster_weights = np.zeros(len(clusters))
        for i, c in enumerate(clusters):
            d = self.query._distances[cluster.indices,:][:,c.indices]
            cluster_weights[i] = np.exp( -2.*np.amin(d) / self.query._max_distance )
        for i in range(1, self.query._close_suboptimal_cluster_size_range[1] + 1):
            cluster_weights[cluster_size_indices[i-1]:cluster_size_indices[i]] /= i
        index = choose_random_weighted_interval( cluster_weights )
        for size, csi in enumerate(cluster_size_indices):
            if not index >= csi:
                break
        true_index = index - cluster_size_indices[size-1]
        
        cluster2 = self.clusters[size].pop(true_index)
        self.potential_clusters1[size].append(cluster2)
        return cluster2
        
        
        
        
    
    def find_cluster_path(self, cluster1, cluster2):
        indices_in = set(cluster1.indices)
        indices_to = set(cluster2.indices)
        arrived = False
        while not arrived:
        
            indices_out = np.array([i for i in self.indices if i not in indices_in])
            pointing1, pointing2 = cluster1.find_closest_pointings(cluster2)
            print(pointing1.index,pointing2.index)
            
            num_points = min(self.query._cluster_size_range[1]*4, len(indices_out))

            sortable_pointings = [i for i in range(num_points)]
            distances = self.query._distances[pointing1.index,indices_out]
            print()
            print(num_points)
            print(sortable_pointings)
            print(distances)
            close_indices = indices_out[np.argpartition(distances, sortable_pointings)[:num_points]]
            print(close_indices)
            print()
            close_indices_weights = np.zeros(num_points)
            for i in range(num_points):
                d = self.query._distances[pointing1.index, close_indices[i]]
                a = pointing1.angle_between_three_pointings(pointing2, self.query._pointings[close_indices[i]])
                if d < self.query._max_distance:
                    close_indices_weights[i] = np.exp(-3. * d / self.query._max_distance) * np.cos(a/2)**4
            index = choose_random_weighted_interval(close_indices_weights)
            if index is None:
                return False
            cluster1 = self.query._pointings[index].cluster
            indices_in = indices_in | set(cluster1.indices)
            if close_indices[index] in indices_to:
                arrived = True
            else:
                self.clusters[cluster1.size].remove(cluster1)
                self.potential_clusters1[cluster1].append(cluster1)
            
            arrived = True #################
        return True
        
        
        
        
        
    
    def calc_cluster_cost(self, clusters):
        pass
    
    def recluster_pointings(self, pointings):
        pass # make preference probabilistic
    
    def has_suboptimal_clusters(self):
        s = 0
        for i in range(self.query._suboptimal_cluster_size_range[0], 
                       self.query._suboptimal_cluster_size_range[1] + 1):
            s += len(self.clusters[i])
        if s >= 2:
            return True
        elif s >= 1:
            for i in range(self.query._suboptimal_cluster_size_range[1] + 1,
                           self.query._close_suboptimal_cluster_size_range[1] + 1):
                s += len(self.clusters[i])
            if s >= 2:
                return True
        return False
            
        






In [581]:
searchquerry = SearchQuery(object_name="Cyg X-1", resultmax=0)
cat = IntegralQuery(searchquerry)
f = Filter(SCW_TYPE="POINTING")
scw_ids = cat.apply_filter(f,True)

In [582]:
test = ClusteredQuery(scw_ids[:20], 1, 1, 2.8, cluster_size_preference_threshold = (100,100))
#print(test._region_indices)

[19], 0.0
[5, 6, 7], 1.831296171661494
[12, 13, 14], 1.8267541396306226
[8, 9, 10, 11], 1.2999530762680331
[15, 16, 17, 18], 1.2981536904708968
[0, 1, 2, 3, 4], 0.7751899214493297
True
[[0.17564257 0.89737088 2.61885778]]
(0, 0)
19 12

19
(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18)
[2.13134336 2.02585686 2.02037569 2.83672194 2.83398732 0.32954735
 0.94084485 2.6388627  1.9844859  1.99202434 2.82089881 1.96970354
 0.17564257 0.89737088 2.61885778 1.97031682 1.97810561 2.81000306
 1.96682056]
[12  5 13  6 18 11 15 16  8  9  2  1  0 14  7 17 10  4  3]


In [583]:
test = ClusteredQuery(scw_ids[:4], 1, 1, 2.8, cluster_size_preference_threshold = (1,1))

[3], 0.0
[0, 1, 2], 0.08185850791460011
True
[[1.18375462 1.2789768  1.27787504]]
(0, 0)
3 0

3
(0, 1, 2)
[1.18375462 1.2789768  1.27787504]
[0 2 1]


In [584]:
test._sortable_distances

array([[0.        , 0.10729474, 0.11235486, 1.18375462, 0.        ],
       [0.10729474, 0.        , 0.02592593, 1.2789768 , 1.        ],
       [0.11235486, 0.02592593, 0.        , 1.27787504, 2.        ],
       [1.18375462, 1.2789768 , 1.27787504, 0.        , 3.        ]])

In [585]:
a = np.reshape( np.arange(100), (10,10) )
a[[1,4,5],:][:,[3,7,8,9]]

array([[13, 17, 18, 19],
       [43, 47, 48, 49],
       [53, 57, 58, 59]])

In [660]:
a = [1,2,3]
b = {4,5,6}
a = set(a)
a|b


{1, 2, 3, 4, 5, 6}

In [587]:
c = np.reshape( np.random.randint(1000, size=100), (10,10) )
c = np.concatenate((c,np.array([np.arange(10)]).T),axis=1)
d = (0,1,2,3,4)
c

array([[481, 662, 242, 157, 820, 200,  84, 564,  84, 238,   0],
       [ 73, 803, 664, 720, 115, 696, 842, 679, 445, 520,   1],
       [899, 263, 493, 405, 284,  80, 248, 753, 181, 604,   2],
       [112, 524, 795, 962,  38, 747, 181, 446, 300, 536,   3],
       [237, 970, 374, 697,  30, 852, 881, 473, 838, 561,   4],
       [ 65, 975,  90, 306, 688, 617,  56, 598, 723, 726,   5],
       [660, 197, 948, 798, 581, 945, 398, 672, 519, 977,   6],
       [388, 171, 247, 361, 401, 747, 570, 872, 801, 415,   7],
       [706, 866, 211, 287, 274, 997, 217, 310, 627, 384,   8],
       [124, 309, 961,  85, 623, 474, 875, 569, 310, 928,   9]])

In [588]:
c[np.argpartition(c[:,0], d)]

array([[ 65, 975,  90, 306, 688, 617,  56, 598, 723, 726,   5],
       [ 73, 803, 664, 720, 115, 696, 842, 679, 445, 520,   1],
       [112, 524, 795, 962,  38, 747, 181, 446, 300, 536,   3],
       [124, 309, 961,  85, 623, 474, 875, 569, 310, 928,   9],
       [237, 970, 374, 697,  30, 852, 881, 473, 838, 561,   4],
       [481, 662, 242, 157, 820, 200,  84, 564,  84, 238,   0],
       [660, 197, 948, 798, 581, 945, 398, 672, 519, 977,   6],
       [388, 171, 247, 361, 401, 747, 570, 872, 801, 415,   7],
       [706, 866, 211, 287, 274, 997, 217, 310, 627, 384,   8],
       [899, 263, 493, 405, 284,  80, 248, 753, 181, 604,   2]])

In [589]:
d = c[3,[1,2,3,5,6,7]]
e = [i for i in range(6)]
d

array([524, 795, 962, 747, 181, 446])

In [590]:
np.argpartition(d,e)

array([4, 5, 0, 3, 1, 2])

In [591]:
np.unravel_index(np.argmax(c),c.shape)

(8, 5)

In [656]:
a=choose_random_weighted_interval(np.array([0,0,1,0,0,1]))
print(a)

2


In [633]:
print(a)

5


In [662]:
a = np.arange(10)
for i, e in enumerate(a):
    a[i] = i*2
print(a)

[ 0  2  4  6  8 10 12 14 16 18]
