In [1]:
import numpy as np
from numba import njit

In [2]:
a = np.reshape(np.linspace(50,1,50), (2,25))
b = np.reshape(np.linspace(1,75,75), (3,25))
a, b

(array([[50., 49., 48., 47., 46., 45., 44., 43., 42., 41., 40., 39., 38.,
         37., 36., 35., 34., 33., 32., 31., 30., 29., 28., 27., 26.],
        [25., 24., 23., 22., 21., 20., 19., 18., 17., 16., 15., 14., 13.,
         12., 11., 10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.]]),
 array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
         14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.],
        [26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
         39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.],
        [51., 52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63.,
         64., 65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75.]]))

In [3]:
np.append(a, b, axis=0)

array([[50., 49., 48., 47., 46., 45., 44., 43., 42., 41., 40., 39., 38.,
        37., 36., 35., 34., 33., 32., 31., 30., 29., 28., 27., 26.],
       [25., 24., 23., 22., 21., 20., 19., 18., 17., 16., 15., 14., 13.,
        12., 11., 10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.],
       [26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
        39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.],
       [51., 52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63.,
        64., 65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75.]])

In [12]:
a = []
for i in range(10):
    a.append(np.linspace(i,i*5,5))
print(a)
print()
a = tuple(a)
@njit
def test():
    # a = []
    # for i in range(10):
    #     a.append(np.linspace(i,i*5,5))
    for i in range(5):
        print(a[i])

test()

[array([0., 0., 0., 0., 0.]), array([1., 2., 3., 4., 5.]), array([ 2.,  4.,  6.,  8., 10.]), array([ 3.,  6.,  9., 12., 15.]), array([ 4.,  8., 12., 16., 20.]), array([ 5., 10., 15., 20., 25.]), array([ 6., 12., 18., 24., 30.]), array([ 7., 14., 21., 28., 35.]), array([ 8., 16., 24., 32., 40.]), array([ 9., 18., 27., 36., 45.])]

[0. 0. 0. 0. 0.]
[1. 2. 3. 4. 5.]
[ 2.  4.  6.  8. 10.]
[ 3.  6.  9. 12. 15.]
[ 4.  8. 12. 16. 20.]
