In [35]:
from pyspi.utils.function_utils import find_response_version
from pyspi.utils.response.spi_response_data import ResponseDataRMF
from pyspi.utils.response.spi_response import ResponseRMFGenerator
from pyspi.utils.response.spi_drm import SPIDRM
from pyspi.utils.livedets import get_live_dets

import numpy as np


In [36]:
time1 = "051105 061512"
ra, dec = 10., -40.

In [37]:
version = find_response_version(time1)
rsp_base = ResponseDataRMF.from_version(version)
dets = get_live_dets(time=time1, event_types=["single"])

Using the irfs that are valid between 04/07/17 08:20:06 and 09/02/19 09:59:57 (YY/MM/DD HH:MM:SS)


In [38]:
ein = np.array(np.linspace(20,1000,4))
ebounds = np.array(np.linspace(20,1000,4))
d = 0

In [39]:
rsp1 = ResponseRMFGenerator.from_time(time1,  d,
                                            ebounds, ein,
                                            rsp_base)
sd1 = SPIDRM(rsp1, ra, dec)
print(ein)
print(sd1.matrix)

[  20.          346.66666667  673.33333333 1000.        ]
[[13.823791    2.70435285  1.79275684]
 [ 0.          8.53337789  1.70787271]
 [ 0.          0.          6.04052616]]


In [40]:
ein = np.array(np.linspace(20,1000,7))
ebounds = np.array(np.linspace(20,1000,4))


In [41]:
rsp2 = ResponseRMFGenerator.from_time(time1,  d,
                                            ebounds, ein,
                                            rsp_base)
sd2 = SPIDRM(rsp2, ra, dec)
print(ein)
print(sd2.matrix)

[  20.          183.33333333  346.66666667  510.          673.33333333
  836.66666667 1000.        ]
[[14.06299834 15.31597976  2.85573938  2.29760791  1.91975918  1.63880981]
 [ 0.          0.          8.38959361  8.25712902  1.8686086   1.15987021]
 [ 0.          0.          0.          0.          5.73556994  5.82934172]]


In [42]:
print(sd1.matrix[0,0])
print(sd2.matrix[0,:2])

13.82379100056793
[14.06299834 15.31597976]


In [43]:
# should the value from sd1 not lie inbetween the two sd2 values?

In [1]:
import astropy.io.fits as fits
from astropy.table import Table
import astropy.time as at
from datetime import datetime
import numpy as np


In [4]:
data_path = "./main_files/SPI_data/0374"

# Pointings and Start Times
with fits.open(f"{data_path}/pointing.fits") as file:
    t = Table.read(file[1])
    
    pointings = np.array(t["PTID_SPI"])
    
    time_start = np.array(t["TSTART"]) + 2451544.5
    time_start = [at.Time(f"{i}", format="jd").datetime for i in time_start]
    time_start = np.array([datetime.strftime(i,'%y%m%d %H%M%S') for i in time_start])

In [5]:
t

<Table length=71>
PTID_ISOC     PTID_SPI    OBT_START  ...  DEC_SPIX   RA_SPIZ   DEC_SPIZ 
                                     ...    deg        deg       deg    
   str8        str15      uint16[4]  ...  float32    float32   float32  
--------- --------------- ---------- ... ---------- --------- ----------
 03740001 03740001.000000 0 .. 63737 ... -46.588104 229.94302  -37.57425
 03740002 03740002.000000 0 .. 63308 ... -46.369335  230.1961  -37.48927
 03740003 03740003.000000 0 .. 61659 ...  -45.68437 230.99942  -36.81915
 03740004 03740004.000000 0 .. 60025 ... -44.942196 231.72835 -36.096745
 03740005 03740005.000000 0 .. 58374 ... -44.144936  232.3689 -35.334618
 03740006 03740006.000000 0 .. 56748 ...  -43.29776 232.92168  -34.53164
 03740007 03740007.000000 0 .. 55089 ...  -41.49371 234.48235 -36.024696
 03740008 03740008.000000 0 .. 53411 ... -42.318604 233.91713 -36.858116
 03740009 03740009.000000 0 .. 51716 ... -43.092133  233.2629  -37.65576
      ...             ...        ... ...        ...       ...        ...
 03740064 03740064.000000  0 .. 2317 ...  -47.77922 229.69748  -8.723521
 03740065 03740065.000000   0 .. 152 ... -49.778072  229.7015  -8.215153
 03740066 03740066.000000 0 .. 63525 ... -49.795628  231.0554 -6.7787395
 03740067 03740067.000000 0 .. 61371 ... -47.795155 231.15605 -7.3855114
 03740068 03740068.000000 0 .. 59222 ...  -45.79515 231.21161 -7.9940715
 03740069 03740069.000000 0 .. 57075 ...  -43.79564  231.2231  -8.602393
 03740070 03740070.000000 0 .. 54933 ... -41.795567 231.19104  -9.208782
 03740071 03740071.000000 0 .. 52799 ... -41.743732 232.73563 -7.9923353
 03740072 03740072.000000 0 .. 50650 ...  -43.77455 232.80838  -7.357876
 03740073 03740073.000000 0 .. 47715 ... -45.774334 232.78235  -6.769658