In [1]:
from pyspi.utils.function_utils import find_response_version
from pyspi.utils.response.spi_response_data import ResponseDataRMF
from pyspi.utils.response.spi_response import ResponseRMFGenerator
from pyspi.utils.response.spi_drm import SPIDRM
from pyspi.utils.livedets import get_live_dets

import numpy as np


/home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/numba/core/decorators.py:262: NumbaDeprecationWarning: numba.generated_jit is deprecated. Please see the documentation at: https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit for more information and advice on a suitable replacement.
  warnings.warn(msg, NumbaDeprecationWarning)


15:33:05 WARNING   The naima package is not available. Models that depend on it will not be         ]8;id=215467;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=146491;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/astromodels/functions/functions_1D/functions.py#48\48]8;;\
                  available                                                                                        

         WARNING   The GSL library or the pygsl wrapper cannot be loaded. Models that depend on it  ]8;id=390577;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=952719;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/astromodels/functions/functions_1D/functions.py#69\69]8;;\
                  will not be available.                                                                           

         WARNING   The ebltable package is not available. Models that depend on it will not be     ]8;id=312471;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=769881;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/astromodels/functions/functions_1D/absorption.py#36\36]8;;\
                  available                                                                                        

         WARNING   We have set the min_value of K to 1e-99 because there was a postive transform   ]8;id=720256;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/astromodels/core/parameter.py\parameter.py]8;;\:]8;id=522051;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/astromodels/core/parameter.py#704\704]8;;\

         WARNING   We have set the min_value of K to 1e-99 because there was a postive transform   ]8;id=775654;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/astromodels/core/parameter.py\parameter.py]8;;\:]8;id=768105;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/astromodels/core/parameter.py#704\704]8;;\

         WARNING   We have set the min_value of K to 1e-99 because there was a postive transform   ]8;id=642162;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/astromodels/core/parameter.py\parameter.py]8;;\:]8;id=135183;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/astromodels/core/parameter.py#704\704]8;;\

         WARNING   We have set the min_value of K to 1e-99 because there was a postive transform   ]8;id=560165;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/astromodels/core/parameter.py\parameter.py]8;;\:]8;id=645230;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/astromodels/core/parameter.py#704\704]8;;\

         WARNING   We have set the min_value of F to 1e-99 because there was a postive transform   ]8;id=454972;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/astromodels/core/parameter.py\parameter.py]8;;\:]8;id=494586;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/astromodels/core/parameter.py#704\704]8;;\

         WARNING   We have set the min_value of K to 1e-99 because there was a postive transform   ]8;id=742480;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/astromodels/core/parameter.py\parameter.py]8;;\:]8;id=313631;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/astromodels/core/parameter.py#704\704]8;;\

/home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/numba/core/decorators.py:262: NumbaDeprecationWarning: numba.generated_jit is deprecated. Please see the documentation at: https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit for more information and advice on a suitable replacement.
  warnings.warn(msg, NumbaDeprecationWarning)


15:33:05 INFO      Starting 3ML!                                                                     ]8;id=939690;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=720652;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/__init__.py#35\35]8;;\

         WARNING   WARNINGs here are NOT errors                                                      ]8;id=867498;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=266301;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/__init__.py#36\36]8;;\

         WARNING   but are inform you about optional packages that can be installed                  ]8;id=650038;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=288327;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/__init__.py#37\37]8;;\

         WARNING    to disable these messages, turn off start_warning in your config file            ]8;id=615186;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=364638;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/__init__.py#40\40]8;;\

         WARNING   no display variable set. using backend for graphics without display (agg)         ]8;id=460031;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=444979;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/__init__.py#46\46]8;;\

         WARNING   ROOT minimizer not available                                                ]8;id=958820;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=202067;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/minimizer/minimization.py#1345\1345]8;;\

         WARNING   PyGMO is not available                                                      ]8;id=352767;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=766000;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/minimizer/minimization.py#1369\1369]8;;\

         WARNING   The cthreeML package is not installed. You will not be able to use plugins which  ]8;id=816653;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=725471;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/__init__.py#94\94]8;;\
                  require the C/C++ interface (currently HAWC)                                                     

         WARNING   Could not import plugin HAWCLike.py. Do you have the relative instrument         ]8;id=681859;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=623296;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/__init__.py#144\144]8;;\
                  software installed and configured?                                                               

         WARNING   Could not import plugin FermiLATLike.py. Do you have the relative instrument     ]8;id=718817;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=904332;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/__init__.py#144\144]8;;\
                  software installed and configured?                                                               

         WARNING   No fermitools installed                                              ]8;id=596261;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/utils/data_builders/fermi/lat_transient_builder.py\lat_transient_builder.py]8;;\:]8;id=754793;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/utils/data_builders/fermi/lat_transient_builder.py#44\44]8;;\

         WARNING   Env. variable OMP_NUM_THREADS is not set. Please set it to 1 for optimal         ]8;id=907044;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=142896;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/__init__.py#387\387]8;;\
                  performances in 3ML                                                                              

         WARNING   Env. variable MKL_NUM_THREADS is not set. Please set it to 1 for optimal         ]8;id=521905;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=668056;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/__init__.py#387\387]8;;\
                  performances in 3ML                                                                              

         WARNING   Env. variable NUMEXPR_NUM_THREADS is not set. Please set it to 1 for optimal     ]8;id=896261;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=754848;file:///home/moej56153/.pyenv/versions/3.9.13/envs/MT2/lib/python3.9/site-packages/threeML/__init__.py#387\387]8;;\
                  performances in 3ML                                                                              

In [2]:
time1 = "051105 061512"
ra, dec = 10., -40.

In [3]:
version = find_response_version(time1)
rsp_base = ResponseDataRMF.from_version(version)
dets = get_live_dets(time=time1, event_types=["single"])

Using the irfs that are valid between 04/07/17 08:20:06 and 09/02/19 09:59:57 (YY/MM/DD HH:MM:SS)


In [7]:
ein = np.geomspace(20,800,6)
ebounds = np.geomspace(20,200, 6)
d = 0


In [5]:
rsp1 = ResponseRMFGenerator.from_time(time1,  d,
                                            ebounds, ein,
                                            rsp_base)
sd1 = SPIDRM(rsp1, ra, dec)
print(sd1.matrix)

AFS data access did not work. I will try the ISDC data archive.
receiving incremental file list
spi_gti.fits.gz

sent 44 bytes  received 3,924 bytes  7,936.00 bytes/sec
total size is 3,816  speedup is 0.96



WARNING NumbaExperimentalFeatureWarning: Use of isinstance() detected. This is an experimental feature.



[[3.34135444 0.07065866 0.06101409 0.09018018 0.05907349]
 [3.25811535 3.375407   0.06679735 0.15699679 0.09727244]
 [0.         8.60368746 0.95924692 0.47550113 0.18484087]
 [0.         2.12014682 5.82197214 0.70435666 0.38137065]
 [0.         0.         8.99650104 2.79083706 0.98470238]]


In [6]:
rsp2 = ResponseRMFGenerator.from_time(time1,  d,
                                            ebounds[2:], ein,
                                            rsp_base)
sd2 = SPIDRM(rsp2, ra, dec)
print(sd2.matrix)

[[0.         8.60368746 0.95924692 0.47550113 0.18484087]
 [0.         2.12014682 5.82197214 0.70435666 0.38137065]
 [0.         0.         8.99650104 2.79083706 0.98470238]]


In [7]:
print(sd1.matrix[2:, :])

[[0.         8.73891479 1.00888777 0.57688616 0.47322423]
 [0.         2.12014682 5.83787191 0.76633158 0.93230756]
 [0.         0.         9.03481842 2.94091853 2.33429362]]


In [8]:
print(np.array_equal(sd1.matrix[2:, :], sd2.matrix))

True


In [65]:
# Therefore the response matrix changes even if we simply cut off part of the observed energy range
# These should be independent of each other