In [57]:
from pyspi.utils.function_utils import find_response_version
from pyspi.utils.response.spi_response_data import ResponseDataRMF
from pyspi.utils.response.spi_response import ResponseRMFGenerator
from pyspi.utils.response.spi_drm import SPIDRM
from pyspi.utils.livedets import get_live_dets

import numpy as np


In [58]:
time1 = "051105 061512"
ra, dec = 10., -40.

In [59]:
version = find_response_version(time1)
rsp_base = ResponseDataRMF.from_version(version)
dets = get_live_dets(time=time1, event_types=["single"])

Using the irfs that are valid between 04/07/17 08:20:06 and 09/02/19 09:59:57 (YY/MM/DD HH:MM:SS)


In [60]:
ein = np.geomspace(20,800,6)
ebounds = np.geomspace(20,200, 6)
d = 0


In [61]:
rsp1 = ResponseRMFGenerator.from_time(time1,  d,
                                            ebounds, ein,
                                            rsp_base)
sd1 = SPIDRM(rsp1, ra, dec)
print(sd1.matrix)

[[3.36413208 0.13080862 0.074996   0.10984525 0.15860172]
 [3.68511853 3.59088075 0.07487477 0.19133634 0.25866502]
 [0.         8.73891479 1.00888777 0.57688616 0.47322423]
 [0.         2.12014682 5.83787191 0.76633158 0.93230756]
 [0.         0.         9.03481842 2.94091853 2.33429362]]


In [62]:
rsp2 = ResponseRMFGenerator.from_time(time1,  d,
                                            ebounds[2:], ein,
                                            rsp_base)
sd2 = SPIDRM(rsp2, ra, dec)
print(sd2.matrix)

[[ 0.         10.18791689  1.09634603  0.70162617  0.54210095]
 [ 0.          2.12014682  5.85688712  0.82075417  1.04374185]
 [ 0.          0.          9.07821572  3.06293752  2.57124935]]


In [63]:
print(sd1.matrix[2:, :])

[[0.         8.73891479 1.00888777 0.57688616 0.47322423]
 [0.         2.12014682 5.83787191 0.76633158 0.93230756]
 [0.         0.         9.03481842 2.94091853 2.33429362]]


In [64]:
print(np.array_equal(sd1.matrix[2:, :], sd2.matrix))

False


In [65]:
# Therefore the response matrix changes even if we simply cut off part of the observed energy range
# These should be independent of each other