In [1]:
import numpy as np
#from numba import njit
import matplotlib.pyplot as plt
from scipy.stats import poisson

In [24]:
a = np.linspace(0,49,50).reshape(5,10)
a

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]])

In [25]:
np.average(a, axis=0)

array([20., 21., 22., 23., 24., 25., 26., 27., 28., 29.])

In [26]:
b = np.linspace(0,4,5)
b[None,:]

array([[0., 1., 2., 3., 4.]])

In [27]:
b

array([0., 1., 2., 3., 4.])

In [31]:
np.cumsum(b)

array([ 0.,  1.,  3.,  6., 10.])

In [30]:
a*b[:,None]

ValueError: operands could not be broadcast together with shapes (5,10) (1,5) 

In [14]:
c = np.linspace(25,49,25).reshape((5,5))
c

array([[25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34.],
       [35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44.],
       [45., 46., 47., 48., 49.]])

In [15]:
a*c

array([[   0.,   26.,   54.,   84.,  116.],
       [ 150.,  186.,  224.,  264.,  306.],
       [ 350.,  396.,  444.,  494.,  546.],
       [ 600.,  656.,  714.,  774.,  836.],
       [ 900.,  966., 1034., 1104., 1176.]])