In [1]:
import numpy as np

In [43]:
def b_maxL_3(m1, m2, m3, t1, t2, t3, C1, C2, C3):
    mt = m1 + m2 + m3
    tt = t1 + t2 + t3
    Ct = C1 + C2 + C3
    a = -tt
    b = -tt*mt + Ct
    c = Ct*mt - C1*m1 - C2*m2 - C3*m3 -tt*(m1*m2 + m2*m3 + m3*m1)
    d = C1*m2*m3 + C2*m3*m1 + C3*m1*m2 - tt*m1*m2*m3
    print(a,b,c,d)
    D0 = b**2 - 3*a*c
    D1 = 2*b**3 - 9*a*b*c + 27*(a**2)*d
    
    print(D0, D1)
    
    if D0 == 0. and D1 == 0.:
        return -b/(3*a)
    
    C = ((D1 + np.sqrt(D1**2 - 4*D0**3 + 0j)) / 2)**(1/3)
    print(D1**2 - 4*D0**3)
    print(C)
    
    if C==0:
        C = ((D1 - np.sqrt(D1**2 - 4*D0**3 + 0j)) / 2)**(1/3)
        
    x0 = -1/(3*a) * (b + C + D0/C)
    
    if x0.real < 0:
        return 0.
    
    return x0.real
    
    

In [48]:
b_maxL_3(
    2,1,6,
    1,2,0,
    0,0,0,
)

-3 -27 -60 -36
189 -4374
-7873200
(9.000000000000002+10.392304845413264j)


(-1+1.9737298215558337e-16j)

In [50]:
a = 1+1j
a.real

1.0

In [12]:
a = np.linspace(1,100,100).reshape((5,20))
for i in a:
    i[:] *= 2
a

array([[  2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,  22.,
         24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.],
       [ 42.,  44.,  46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,
         64.,  66.,  68.,  70.,  72.,  74.,  76.,  78.,  80.],
       [ 82.,  84.,  86.,  88.,  90.,  92.,  94.,  96.,  98., 100., 102.,
        104., 106., 108., 110., 112., 114., 116., 118., 120.],
       [122., 124., 126., 128., 130., 132., 134., 136., 138., 140., 142.,
        144., 146., 148., 150., 152., 154., 156., 158., 160.],
       [162., 164., 166., 168., 170., 172., 174., 176., 178., 180., 182.,
        184., 186., 188., 190., 192., 194., 196., 198., 200.]])

In [4]:
b = np.linspace(1,5,5)
b

array([1., 2., 3., 4., 5.])

In [10]:
a/b[:,np.newaxis]

array([[ 1.        ,  2.        ,  3.        ,  4.        ,  5.        ,
         6.        ,  7.        ,  8.        ,  9.        , 10.        ,
        11.        , 12.        , 13.        , 14.        , 15.        ,
        16.        , 17.        , 18.        , 19.        , 20.        ],
       [10.5       , 11.        , 11.5       , 12.        , 12.5       ,
        13.        , 13.5       , 14.        , 14.5       , 15.        ,
        15.5       , 16.        , 16.5       , 17.        , 17.5       ,
        18.        , 18.5       , 19.        , 19.5       , 20.        ],
       [13.66666667, 14.        , 14.33333333, 14.66666667, 15.        ,
        15.33333333, 15.66666667, 16.        , 16.33333333, 16.66666667,
        17.        , 17.33333333, 17.66666667, 18.        , 18.33333333,
        18.66666667, 19.        , 19.33333333, 19.66666667, 20.        ],
       [15.25      , 15.5       , 15.75      , 16.        , 16.25      ,
        16.5       , 16.75      , 17.        , 1

In [2]:
from moveable_crab_test import *

[WARNING ] The naima package is not available. Models that depend on it will not be available
[WARNING ] The GSL library or the pygsl wrapper cannot be loaded. Models that depend on it will not be available.
[WARNING ] The ebltable package is not available. Models that depend on it will not be available
[INFO    ] Starting 3ML!
[WARNING ] no display variable set. using backend for graphics without display (agg)
[WARNING ] ROOT minimizer not available
[WARNING ] PyGMO is not available
[WARNING ] The cthreeML package is not installed. You will not be able to use plugins which require the C/C++ interface (currently HAWC)
[WARNING ] Could not import plugin HAWCLike.py. Do you have the relative instrument software installed and configured?
[WARNING ] Could not import plugin FermiLATLike.py. Do you have the relative instrument software installed and configured?
[WARNING ] No fermitools installed
[WARNING ] Env. variable OMP_NUM_THREADS is not set. Please set it to 1 for optimal performances 

In [3]:
folder = "movable_crab_1644_pair"

# save_pair_clusters(
#     (("crab_data/1644", '164400150010', '164400220010'),),
#     folder
# )

pointings = (("crab_data/1644", '164400150010', '164400220010'),)
source_model = define_sources((
    (crab_pl_free_pos, (40,)),
))

multinest_for_pointing_pairs(
    folder,
    pointings,
    source_model,
    rebin_data_exp,
    (None, 80),
    np.geomspace(18, 150, 50)
)

Using the irfs that are valid between 10/05/27 12:45:00 and present (YY/MM/DD HH:MM:SS)
 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points =  800
 dimensionality =    4
 *****************************************************
 Starting MultiNest
 generating live points
Using the irfs that are valid between 10/05/27 12:45:00 and present (YY/MM/DD HH:MM:SS)
Using the irfs that are valid between 10/05/27 12:45:00 and present (YY/MM/DD HH:MM:SS)
Using the irfs that are valid between 10/05/27 12:45:00 and present (YY/MM/DD HH:MM:SS)
Using the irfs that are valid between 10/05/27 12:45:00 and present (YY/MM/DD HH:MM:SS)
Using the irfs that are valid between 10/05/27 12:45:00 and present (YY/MM/DD HH:MM:SS)
Using the irfs that are valid between 10/05/27 12:45:00 and present (YY/MM/DD HH:MM:SS)
Using the irfs that are valid between 10/05/27 12:45:00 and present (YY/MM/DD HH:MM:SS)
Using the irfs tha